MODEL:
  TYPE: hivit
  NAME: hivit_small_224
  DROP_PATH_RATE: 0.3
  VIT:
    PATCH_SIZE: 16
    INNER_PATCHES: 4
    EMBED_DIM: 384
    DEPTHS: [2, 2, 20]
    NUM_HEADS: 6
    STEM_RATIO: 3.
    MLP_RATIO: 4.
    APE: True
    RPE: True
TRAIN:
  CLIP_GRAD: None