MODEL:
  TYPE: hivit
  NAME: hivit_base_224
  DROP_PATH_RATE: 0.5
  VIT:
    PATCH_SIZE: 16
    INNER_PATCHES: 4
    EMBED_DIM: 512
    DEPTHS: [2, 2, 20]
    NUM_HEADS: 8
    STEM_RATIO: 3.
    MLP_RATIO: 4.
    APE: True
    RPE: True
TRAIN:
  CLIP_GRAD: None